### ISSUE TITLE
Předělání zda skript běží přes příkazový řádek.

### ISSUE THREAD

**Issue by ondrani** [patrick11514/php-ssh-mysql-backup#1]
Použil bych spíše
```php
if (PHP_SAPI !== 'cli') exit;
```

**Comment by patrick11514** [comment]
Dobrý den, zatím neplánuji měnit kontrolu, toho zda to otevírám přes prohlížeč. Pokud by se ale přeci našel bug, kdy ti v prohlížeči otevřít půjde, opravím to podle vás.
